title: "Edmond Fossi"
description: "Data Scientist | Mathématicien Appliqué | Modelisation"
theme: jekyll-theme-minimal # Thèmes : cayman, minima, slate, midnight, etc.
logo : tof.jpg
# Liens / Méta
avatar: "/tof.jpg"
