title: "Portfolio - Edmond Fossi"
description: "Data Scientist | Mathématicien Appliqué"
theme: jekyll-theme-minimal # Thèmes : cayman, minima, slate, midnight, etc.
header_pages:
  - index.md

# Liens / Méta
avatar: "/tof.jpg"
